admin: {rule: admin_logged_in, handler: redirect_to_admin_login}
admin.auth.login: {rule: allowed_to_auth_admin, handler: redirect_to_admin_index}
admin.auth.logout: {rule: admin_logged_in, handler: forbidden}

admin.cms.add-page:    {rule: allowed_add_cms_page,    handler: forbidden_if_admin_authorized}
admin.cms.edit-page:   {rule: allowed_edit_cms_page,   handler: not_found_if_admin_authorized}
admin.cms.delete-page: {rule: allowed_delete_cms_page, handler: not_allowed_work_with_cms_page}
  
cms.index.index:       {rule: cms_page_exists,         handler: not_found}


change-cms-page-name:  {rule: change_page_name_allowed}
change-cms-page-route: {rule: change_page_route_allowed}
delete-cms-pages:      {rule: delete_page_allowed}
