user.index.index: {rule: user_logged_in_or_in_params, handler: not_detected_user}
user.auth.login: {rule: allowed_to_auth, handler: redirect_to_user_index}
user.auth.logout: {rule: _TRUE_}
user.register.register: {rule: !logged_in, handler: redirect_to_user_index}
user.register.confirmation: {rule: not_logged_in_and_user_exist_by_email_and_role_and_not_confirmed, handler: not_found}
