<div class="auth-form login">

    <h1 class="page-header center">Log in</h1>

    <?=$this->form;?>
    
    <ul class="auth-links">
        <li><a href="<?php echo $this->url(array(), 'UserAuthForgotPassword'); ?>" />Forgot Password?</a></li>
        <li><a href="<?php echo $this->url(array(), 'UserRegisterRegister'); ?>">Sign Up</a></li>
    </ul>
    
    <div class="clear"><!-- --></div>
</div>