<?=$this->form('search', array(
	'action' => $this->url(array(), 'ImageLibraryFileGet'),
	'method' => $this->form->getMethod(),
	'id' => 'search',
))?>

	<table class="img_lib_search" style="width:288px;" border="0" align="right" cellpadding="0" cellspacing="0">
		<tr>
			<td width="64%" align="left" valign="top">
				<?=$this->form->occurance
                    ->setAttrib('class', 'm_input')
                    ->setAttrib('placeholder', 'Search an image by its name')
                    ->renderViewHelper()?>
			</td>
			<td width="36%" align="left" valign="top">
				<?=$this->form->folder->setAttrib('class', 'm_dropdown')->renderViewHelper()?>
			</td>
		</tr>
        <tr>
            <td style="text-align:right;"><input type="submit" value="" /></td>
            <td></td>
        </tr>
	</table>
	
</form>

<script type="text/javascript">
$(function()
{

    $('input[placeholder]').each(function()
    {
        inputPlaceholder(this);
    });

});
</script>
