<?php
$item = new stdClass();
$item->descriptionhead = "Дизайн интерьера это больше, чем свежие обои на стенах, новая мебель и техника. Не сделают ваш интерьер красивее и гармоничнее дорогие отделочные материалы. Ведь в дизайне интерьера важна каждая мелочь, важна мысль - идея, а не стоимость и новизна. Мы придерживаемся гибкой ценовой политики.";
$item->keywordshead = "Дизайн интерьера, Дизайн спальни, Дизайн гостинной, Дизайн столовой, Дизайн санузлов, Дизайн детской, Дизайн дома, Кухни на заказ";
$item->titlehead = "Дизайн интерьера";
$this->addHelperPath('../application/modules/default/views/helpers/', 'Default_View_Helper');
echo $this->headertag($item);
?>
<div class="container_24">
<div class="grid_24">
<div class="overflow">
<div id="slider" class="nivoSlider"
	style="position: relative; background-image: url(/images/morda/slide-1.jpg); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; background-position: initial initial; background-repeat: no-repeat no-repeat;">
<img src="/images/morda/slide-1.jpg" /> <img
	src="/images/morda/slide-2.jpg" /> <img src="/images/morda/slide-3.jpg" />
<img src="/images/morda/slide-4.jpg" /> <img
	src="/images/morda/slide-5.jpg" /> <img src="/images/morda/slide-6.jpg" />
<img src="/images/morda/slide-7.jpg" /></div>
</div>
</div>
</div>



<div class="primary_content_wrap">
<div class="container_24 clearfix">
<div class="grid_24">
<div class="wrapper">
<div class="line-ver">
<div class="grid_12 prefix_1 suffix_1 alpha">
<div class="wrapper">
<div id="text-6">
<h2>Стиль, Качество, Комфорт!</h2>
<div class="textwidget">
<div class="images"><i><img src="/images/img-4.jpg" alt="Дизайн домов"></i>
<img src="/images/img-5.jpg" alt="Дизайн квартир"></div>
<h6>&nbsp;</h6>
<a href="/2/worksview.html">Дизайн интерьера</a> это больше, чем свежие
обои на стенах, новая <a href="/5/worksview.html">мебель</a> и техника.
Не сделают ваш интерьер красивее и гармоничнее дорогие отделочные
материалы. Ведь в дизайне интерьера важна каждая мелочь, важна мысль -
идея, а не стоимость и новизна. Мы придерживаемся гибкой <a
	href="/price_interior.html">ценовой политики.</a>
</p>
<div class="link"></div>

<div
	style="height: 28px; width: 376px; text-align: left; padding-bottom: 7px; padding-left: 10px; padding-right: 10px; padding-top: 7px;">
<script type="text/javascript" src="//yandex.st/share/share.js"
	charset="utf-8"></script>
<div class="yashare-auto-init" data-yashareL10n="ru"
	data-yashareType="none"
	data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,lj,friendfeed,moikrug"></div>
</div>
</div>

</div>
</div>
</div>
<div class="grid_8 prefix_1 suffix_1 omega">
<div class="wrapper">
<div id="my_poststypewidget-2">
<h2>Текущие проекты:</h2>
<ul class="post_list posts">
	<li class="cat_post_item-1 clearfix"><a class="post-title"
		href="/13/work.html" rel="bookmark" title="Бирюзовая кухня">Бирюзовая
	кухня</a>
	<div></div>
	<div class="post_content">Процесс изготовления и установки кухни с
	фасадами из крашенного МДФ.</div>
	</li>
	<li class="cat_post_item-2 clearfix"><a class="post-title"
		href="/14/work.html" rel="bookmark" title="Салон красоты">Салон
	красоты</a>
	<div></div>
	<div class="post_content">Процесс реализация дизайн-проекта салона
	красоты по ул. Ольшевского.</div>
	</li>
	<li class="cat_post_item-3 clearfix"><a class="post-title"
		href="/5/work.html" rel="bookmark" title="ЛАКОНИЧНОСТЬ И КОМФОРТ">Лаконичность
	и комфорт</a>
	<div></div>
	<div class="post_content">Завершена реализация дизайн-проекта квартиры
	по ул.Матусевича.</div>
	</li>
</ul>
</div>
</div>
</div>
</div>
</div>
<!--.wrapper--></div>
<!--.grid_24--></div>
<!--.container--></div>
<!--.primary_content_wrap-->