		<link href="/css/default.css" rel="stylesheet" type="text/css" />
		<link href="/css/uploadify.css" rel="stylesheet" type="text/css" />
		<link href="/css/jquery.Jcrop.css" rel="stylesheet" type="text/css" /> 
		<script type="text/javascript" src="/scripts/swfobject.js"></script>
		<script type="text/javascript" src="/scripts/jquery.uploadify.v2.1.4.min.js"></script>
		<script type="text/javascript" src="/scripts/jquery-impromptu.3.1.min.js"></script>
		<script type="text/javascript" src="/scripts/jquery.Jcrop.min.js"></script>
		<script type="text/javascript" src="/scripts/jquery-uberuploadcropper.js"></script> 

<div id="zendform" class="zendform">
<form enctype="application/x-www-form-urlencoded" class="global_form" id="editform" action="" method="post">
<div><h3>ADS</h3> 
<div class="form-elements"> 
<dl class="zend_form">
<?=$this->form->url?>
<?=$this->form->status?>
<?=$this->form->description?>
<?=$this->form->submit?>
</dl>
</div>
</div>
</form>
</div>
<BR><BR><BR>