routes:
  DefaultIndexIndex:
    type: Zend_Controller_Router_Route_Static
    route:
    defaults:
      module: default
      controller: index
      action: index
  DefaultIndexWorksview:
    type: Zend_Controller_Router_Route
    route: /:category_id/worksview.html
    defaults:
      module: default
      controller: index
      action: worksview
  DefaultIndexWorkview:
    type: Zend_Controller_Router_Route
    route: /:work_id/work.html
    defaults:
      module: default
      controller: index
      action: workview

#   need the last line, for some reason it is not parse by Zend_Config_Yaml