<script type="text/javascript">
$(function()
{
    <? // think this not work ?>
	$(document).data('sitegift_id', <?=$this->sitegift_id?>);
	$(document).data('imagelibrary_dir', "<?=ImageLibrary_Utils::getDir($this->sitegift_id)?>");
});
</script>

<div class="image_library_popup" id="popupFilemanager" style="display: none;">

<?=$this->partial('context-menu/folder.phtml')?>
<?=$this->partial('context-menu/file.phtml')?>

    <table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
            <td align="center" valign="middle">
                <table width="964" border="0" align="center" cellpadding="0" cellspacing="0">
                    <tr>
                        <td align="left" valign="top">
                            <div class="d_top"></div>
                            <div class="d_left"></div>
                            <div class="d_content">
                                <div class="d_close"><a href="javascript:void(0);" class="close_popup"><img src="images/img_popup_close.jpg" alt="Close" border="0" /></a></div>
                                <div class="d_title">my image library</div>

								<div class="manage_left">
                                    <h1 class="manage_title">My Folders</h1>
									<?=$this->partial('index/_folders.phtml', array(
										'folders' => $this->folders
									))?>
                                    
                                    <a href="javascript:void(0);" id="new_folder"><!-- New Folder --></a>
                                    
                                    <? if ($this->is_upload_enabled) : ?><div class="upl_img_wrapper">Upload New File:<? endif; ?><?=$this->partial('index/form/upload.phtml', array(
                                        'form' => $this->form['upload'],
                                        'is_upload_enabled' => $this->is_upload_enabled, 
                                    ))?><? if ($this->is_upload_enabled) : ?></div><? endif; ?>
                                    
                                </div>

                                <div class="manage_right">
                                    <table width="652" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                            <td colspan="3" align="left" valign="top" class="manage_title">
                                                <span style="display:block;height:22px;font-size:22px;line-height:22px;">Images</span>
                                                <span style="display:block;height:11px;font-size:11px;line-height:11px;">Pre-select any image with your mouse first, then click on "Select This Image" OR "Edit This Image" at the bottom of this window.</span>
                                            </td>
                                            <? /* <td width="372" align="right" valign="top">
												<?=$this->partial('index/_space.phtml', array(
													'space' => $this->space,
												))
											</td> */ ?>
                                        </tr>
                                        <tr>
                                            <td colspan="3" class="m_margin">
												<div class="m_box">
												
												<?=$this->partial('index/_files.phtml', array(
													'files' => $this->files,
                                                    'cache' => $this->cache, 
												))?>
												
												</div>
											</td>
                                        </tr>
                                        <tr>
                                            <td style="vertical-align:top;width:170px;" align="left" valign="top">
												<a class="img_lib_select" href="javascript:void(0)"><!-- Select this image --></a>
                                            </td>
                                            <td style="vertical-align:top;width:170px;">
                                                <a id="edit_image" class="img_lib_edit" href="javascript:void(0)"><!-- Edit this image --></a>
											</td>
                                            <td align="right" valign="middle">
												<?=$this->partial('index/form/search.phtml', array(
													'form' => $this->form['search'],
												))?>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                            <div class="d_right"></div>

                            <div class="d_bottom"></div>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>