		<script type="text/javascript" src="/scripts/ariy.validator.js"></script>
		<link href="/css/default.css" rel="stylesheet" type="text/css" />
		<link href="/css/uploadify.css" rel="stylesheet" type="text/css" />
		<link href="/css/jquery.Jcrop.css" rel="stylesheet" type="text/css" /> 
		<script type="text/javascript" src="/scripts/swfobject.js"></script>
		<script type="text/javascript" src="/scripts/jquery.uploadify.v2.1.4.min.js"></script>
		<script type="text/javascript" src="/scripts/jquery-impromptu.3.1.min.js"></script>
		<script type="text/javascript" src="/scripts/jquery.Jcrop.min.js"></script>
		<script type="text/javascript" src="/scripts/jquery-uberuploadcropper.js"></script> 
<script type="text/javascript">
$(document).ready(function() {
	if ($('#purchase_id').val() == '') {
		$('#status').attr('disabled', true);
		$("#status").val("0");
		}
	else {
		$('#status').attr('disabled', false);
		}
	$('#purchase_id').change(function() {
		if ($('#purchase_id').val() == '') {
			$("#status").val("0");
			$('#status').attr('disabled', true);
			}
		else {
			$('#status').attr('disabled', false);
			}
		});

   	$('#price').ariyValidate({
		type: "price",
		error_message: "Error"
	});
	$('#custom').ariyValidate({
		type: "price",
		on_error: function(str) {
		  $('#log').html($('#log').html()+"<br />"+str+" is not valid value!");
		},
		disable_message: true		
	});
	$('#submit').click(function(){
		$('input').each(function(){
			if (!this.validate()) alert(this.options.error_message);
		});
	});


	$('#UploadPhoto').uberuploadcropper({
		//---------------------------------------------------
		// uploadify options..
		//---------------------------------------------------
		'uploader'  : '/scripts/uploadify.swf',
		'script'    : '/uploadify/uploadify.php',
		'cancelImg' : 'cancel.png',
		'multi'     : false,
		'auto'      : true,
		'folder'    : '/uploads',
		'fileDesc'  : 'JPG',
		'fileExt'   : '*.jpg;*.jpeg',
		//---------------------------------------------------
		//now the cropper options..
		//---------------------------------------------------
		'aspectRatio': 1, 
		'allowSelect': false,			//can reselect
		'allowResize' : true,			//can resize selection
		'setSelect': [ 0, 0, 246, 246 ],	//these are the dimensions of the crop box x1,y1,x2,y2
		'minSize': [ 246, 246 ],		//if you want to be able to resize, use these
		//'maxSize': [ 100, 100 ],
		/*
		onError: function (a, b, c, d) {
			if (d.status == 404)
				alert('Could not find upload script. Use a path relative to: '+'W:\home\test1.ru\www');
			else if (d.type === "HTTP")
				alert('error '+d.type+": "+d.status);
			else if (d.type ==="File Size")
				alert(c.name+' '+d.type+' Limit: '+Math.round(d.sizeLimit/1024)+'KB');
			else
				alert('error '+d.type+": "+d.text);
		},*/
		//---------------------------------------------------
		//now the uber options..
		//---------------------------------------------------
		'cropScript': '/uploadify/crop.php',
		'onComplete': function(imgs,data){ 
			$('#PhotoPrev').attr('src','/uploads/'+imgs[0].name +'?d='+ (new Date()).getTime()); 
			$('#file').attr('value','/uploads/'+imgs[0].name);
		}
	});
	
});
</script>
<div style="position:relative; left:140px;"><a href="/admin/puzzle/<?=$this->pack->id;?>/index.html"><b><?=$this->escape($this->pack->name)?></b></a></div><BR>
<form enctype="multipart/form-data" action="" method="post"><dl class="zend_form">
<?=$this->form->name;?>
<?=$this->form->category_id;?>
<?=$this->form->status;?>
<?=$this->form->price;?>
<?=$this->form->purchase_id;?>
<?=$this->form->description;?>
<?=$this->form->file;?>
		<input type="file" name="UploadPhoto" id="UploadPhoto" /> 
		<img src="photo_not_available.png" id="PhotoPrev" alt="Photo Preview" />
<?=$this->form->submit;?>
</dl></form>

<div align="left" style="padding-left:140px;">246 image<BR><img src="/packs/<?=$this->pack->id?>/<?=$this->pack->image246?>"></div><BR>
<div align="left" style="padding-left:140px;">123 image<BR><img src="/packs/<?=$this->pack->id?>/<?=$this->pack->image123?>"></div>


<BR><BR><BR>








