 <footer id="footer">
      <div class="container_24">
            <div class="grid_24">
                           <div id="footer-widget-area">
                  <div class="indent">
                     <div class="line-ver-1">
                        <div class="line-ver-2">
                           <div class="inner">
                              <div class="wrapper">
                                 
                                 <div class="footer-area-1 grid_8 alpha">
                                    <div id="nav_menu-3"><h4>Дизайны:</h4><div class="menu-our-products-container">
<ul id="menu-our-products" class="menu">
<li id="menu-item-10" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-10 even"><a href="/dezain_spalny.html">Дизайн спальни</a></li>
<li id="menu-item-11" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-11"><a href="/dezain_gostinnoi.html">Дизайн гостинной</a></li>
<li id="menu-item-12" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-12 even"><a href="/dezain_stolovoi.html">Дизайн столовой</a></li>
<li id="menu-item-13" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-13"><a href="/dezain_sanuzlov.html">Дизайн санузлов</a></li>
<li id="menu-item-14" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-14 even"><a href="/dezain_detskoi.html">Дизайн детской</a></li>
<li id="menu-item-15" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-15"><a href="/dezain_doma.html">Дизайн дома</a></li>
<li id="menu-item-16" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-16 even"><a href="/kuhni_na_zakaz.html">Кухни на заказ</a></li>
</ul></div></div>                                 </div>
                                 
                                 <div class="footer-area-2 grid_5 prefix_1 suffix_1">
                                    <div id="text-5"><h4>Контакты</h4>            
                                    <div class="textwidget"><ul class="list">
  <li><img src="/images/icon-1.png" alt="">GSM: +375 44 7369537</li>
  <li><img src="/images/icon-2.png" alt=""><a href="#"><img src="/images/mail.gif"></a></li>
  <li><img src="/images/icon-4.png" alt=""><a href="skype:frauritterrot?call">frauritterrot</a></li>
</ul></div>
        </div>                                 </div>
                                 
          <div class="footer-area-3 grid_7 omega">
           <div id="my_cyclewidget-2">
            <h4>Партнёры</h4>                        
              <div id="testi-controls">
                <ul id="nav-testi"><li class="">Салон итальянской плитки и сантехники «СКВИРЕЛ»</li>
                <li class="">Салон испанской плитки «СМАЛЬТА»</li>
                <li class="">Салон польской плитки «Опочно»</li>
                <li class="">Салон обоев «КРЕА»</li>
                </ul>
              </div>
                            <!-- end of testimonials -->
              
            
            
                                      </div>                                         </div>
                                 
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
                        
                            
            <div class="footer-info">
                <div class="inner">
                <div class="wrapper">
               
                     <div class="footer-area-4">
                     </div>
           
<p><i><a href="http://livedemo00.template-help.com/wordpress_35922/" title="Modern interior design trends" class="site-name">doit.by</a></i> © 2007 | <a href="privacy-policy">Privacy policy</a> <span><!-- {%FOOTER_LINK} --></span></p>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-28394864-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
                  </div>

               </div>

            </div>

        

         </div>

      </div><!--.container-->

   </footer>

   

</div><!--#main-->
</body>
</html>