<!DOCTYPE html>
<html dir="ltr" lang="ru-RU" class=" js flexbox canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
      
    <?php echo $this->headTitle()?>
    <?php echo $this->headMeta()?>
   
  <meta name="viewport" content="width=device-width,initial-scale=1">
	<meta charset="UTF-8">
    <link rel="icon" href="/images/favicon.ico" type="image/x-icon">
	<!-- The HTML5 Shim is required for older browsers, mainly older versions IE -->
	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
   <!--[if lt IE 7]>
     <div style=' clear: both; text-align:center; position: relative;'>
       <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
         <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
      </a>
    </div>
   <![endif]-->
  <link rel="stylesheet" type="text/css" media="all" href="/css/normalize.css">
  <link rel="stylesheet" type="text/css" media="all" href="/css/style.css">
  <link rel="stylesheet" type="text/css" media="all" href="/css/prettyPhoto.css">
  <link rel="stylesheet" type="text/css" media="all" href="/css/grid.css">
  <link media="screen" rel="stylesheet" href="/css/colorbox.css" />
  <link rel="stylesheet" href="/css/nivo-slider.css" type="text/css" media="screen" />
  <link href="/css/css.css" rel="stylesheet" type="text/css">
  <link href="/css/css1.css" rel="stylesheet" type="text/css">
  <link href="/css/css2.css" rel="stylesheet" type="text/css">
  <link rel="stylesheet" id="contact-form-7-css" href="/css/styles.css" type="text/css" media="all">
  <link rel="stylesheet" id="wp-pagenavi-css" href="/css/pagenavi-css.css" type="text/css" media="all">
  <script type="text/javascript" src="/js/l10n.js"></script>
  <script type="text/javascript" src="/js/jquery-1.6.4.min.js"></script>
  <script  type="text/javascript" src="/js/jquery.colorbox-min.js"></script>
  <script  type="text/javascript" src="/js/superfish.js"></script>
  <script src="/js/jquery.nivo.slider.pack.js" type="text/javascript"></script>
  <script type="text/javascript" src="/js/jquery.loader.js"></script>
  <script type="text/javascript" src="/js/swfobject.js"></script>
  <script type="text/javascript" src="/js/custom.js"></script>

  <!--[if lt IE 9]>
  <style type="text/css">
    .border {
      behavior:url(/css/PIE.php)
      }
  </style>
  <![endif]-->
  
  
   <script type="text/javascript">
        $(window).load(function() {
            jQuery(function(){
                jQuery('ul.sf-menu').superfish({
                    delay:       1000,      // one second delay on mouseout 
                    animation:   {opacity:'show',height:'show'}, // fade-in and slide-down animation 
                    speed:       'normal',  // faster animation speed 
                    autoArrows:  true,   // generation of arrow mark-up (for submenu) 
                    dropShadows: false   // drop shadows (for submenu)
                });
            });
            
            jQuery('#slider').nivoSlider({
                effect: 'random', // Specify sets like: 'fold,fade,sliceDown'
                slices: 15, // For slice animations
                boxCols: 8, // For box animations
                boxRows: 4, // For box animations
                animSpeed: 1200, // Slide transition speed
                pauseTime: 3500, // How long each slide will show
                startSlide: 0, // Set starting Slide (0 index)
                directionNav: true, // Next & Prev navigation
                directionNavHide: true, // Only show on hover
                controlNav: true, // 1,2,3... navigation
                controlNavThumbs: false, // Use thumbnails for Control Nav
                controlNavThumbsFromRel: false, // Use image rel for thumbs
                controlNavThumbsSearch: '.jpg', // Replace this with...
                controlNavThumbsReplace: '_thumb.jpg', // ...this in thumb Image src
                keyboardNav: true, // Use left & right arrows
                pauseOnHover: true, // Stop animation while hovering
                manualAdvance: false, // Force manual transitions
                captionOpacity: 0.8, // Universal caption opacity
                prevText: 'Прев', // Prev directionNav text
                nextText: 'След', // Next directionNav text
                beforeChange: function(){}, // Triggers before a slide transition
                afterChange: function(){}, // Triggers after a slide transition
                slideshowEnd: function(){}, // Triggers after all slides have been shown
                lastSlide: function(){}, // Triggers when last slide is shown
                afterLoad: function(){} // Triggers when slider has loaded
            });
        });
        </script>
  <!-- Custom CSS -->
  <style type="text/css">
		/* Body styling options */
				
  	/* Header styling options */
				
		/* Links and buttons color */
				
		/* Body typography */
		body {font-family:Arial, Helvetica, sans-serif; color:#333}#main {font-size:12px; font-style:normal;}  </style>
</head>

<body class="page page-id-290 page-child parent-pageid-24 page-template page-template-page-Portfolio1Col-php">
   <header id="header">
      <div class="container_24">
         <div class="grid_24">
         
            <div id="header-area-1">
					<div id="text-3" class="widget-header"><h3></h3>			
					
		</div>            </div>
		<!--#widget-header-->
            
            <div id="header-area-2">
					<div id="widget_text" class="widget-header"><h3>Для посетителя</h3>			
					<div class="textwidget">
						<div class="buttons"></div>
					</div>
					</div>
					<div id="widget_nav_menu" class="widget-header"><h3>Меню</h3>
					<div class="menu-extra-menu-container">
                        <ul id="menu-extra-menu" class="menu">
                            <li id="menu-item-136" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-136">
                                <a>GSM: +375 44 7369537</a>
                            </li>
                            <li id="menu-item-135" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-135">
                                <a href="skype:frauritterrot?call">Skype: frauritterrot</a>
                            </li>
                            <li id="menu-item-6" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-6">
                                <a>ICQ: 34324687</a>
                            </li>
                            
                        </ul>
					</div>
					</div>            
			</div>
			<!--#widget-header-->
            <div class="logo">
              <a href="/" id="logo"><img src="/images/logo.png" width="288px" height="59px" alt="doit.by" title="Modern interior design trends"></a>
            </div>
<?php 
//print_r($_SERVER);

//menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-30 current_page_item menu-item-49
//menu-item menu-item-type-post_type current_page_item menu-item-object-page menu-item-49

$home = '';
if ($_SERVER['REQUEST_URI']=='/') {
    $home = 'current_page_item';
};
//[REQUEST_URI] => /user/register.html
?>
           <nav class="primary">
             <ul id="topnav" class="sf-menu sf-js-enabled"><li id="menu-item-49" class="menu-item menu-item-type-post_type <?=$home?> menu-item-object-page menu-item-49"><a href="/">Главная</a></li>
<li id="menu-item-50" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-50">
<a class="sf-with-ul">Интерьеры<span class="sf-sub-indicator"> »</span></a>
<ul style="visibility: hidden; display: none;" class="sub-menu">
    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-51" id="menu-item-51"><a href="/style.html">Стили</a></li>
    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-52" id="menu-item-52"><a href="/services_interior.html">Услуги</a></li>
    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-53" id="menu-item-53"><a href="/price_interior.html">Цены</a></li>
 </ul>
</li>

<li id="menu-item-51" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-51"><a class="sf-with-ul">Мебель</a>
<ul style="visibility: hidden; display: none;" class="sub-menu">
    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-51" id="menu-item-51"><a href="/style_furniture.html">Стили</a></li>
    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-52" id="menu-item-52"><a href="/furniture_materials.html">Материалы</a></li>
    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-53" id="menu-item-53"><a href="/price_furniture.html">Цены</a></li>
 </ul>
</li>
<li id="menu-item-58" class="menu-item menu-item-type-post_type menu-item-object-page current-page-ancestor current-menu-ancestor current-menu-parent current-page-parent current_page_parent current_page_ancestor menu-item-58">
    <a class="sf-with-ul">ПОРТФОЛИО<span class="sf-sub-indicator"> »</span></a>
    <ul class="sub-menu" style="display: none; visibility: hidden; ">
<?php 
    $categories = Doctrine::getTable('Category')->findByParams(array(
        'order_by' => array('field'=>'position','direction'=>'asc')
    ));
    foreach ($categories as $key=>$category) {
        $item_id = 300 - $category->id; 
?>
	<li id="menu-item-<?=$item_id?>" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-<?=$item_id?>"><a href="/<?=$category->id?>/worksview.html"><?=$this->escape($category->title);?></a></li>
<?php 
    }
?>

    </ul>
</li>
<li id="menu-item-59" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-59"><a href="/under_construction.html">Арт галлерея</a></li>
</ul>           </nav><!--.primary-->
        
				        
         </div>
      </div><!--.container-->
   </header>
<div id="main">